enum
{
	NUM_ATTRIBUTES = 91,
	SHIFT_INDEX = 79,
	LEFT_SHIFT_INDEX = 52,
	RIGHT_SHIFT_INDEX = 77,
	CONTROL_INDEX = 17,
	LEFT_CONTROL_INDEX = 51,
	RIGHT_CONTROL_INDEX = 76,
	ALT_INDEX = 12,
	LEFT_ALT_INDEX = 49,
	RIGHT_ALT_INDEX = 74,
	COMMAND_INDEX = 16,
	LEFT_COMMAND_INDEX = 50,
	RIGHT_COMMAND_INDEX = 75,
};
