enum
{
	NUM_PARAMETERS = 90,
	SHIFT_INDEX = 85,
	LEFT_SHIFT_INDEX = 65,
	RIGHT_SHIFT_INDEX = 84,
	CONTROL_INDEX = 40,
	LEFT_CONTROL_INDEX = 64,
	RIGHT_CONTROL_INDEX = 83,
	ALT_INDEX = 37,
	LEFT_ALT_INDEX = 62,
	RIGHT_ALT_INDEX = 81,
	COMMAND_INDEX = 39,
	LEFT_COMMAND_INDEX = 63,
	RIGHT_COMMAND_INDEX = 82,
};
