#ifndef digi_Nodes_All_h
#define digi_Nodes_All_h

#include "AnimationNode.h"
#include "BlendPipeNode.h"
#include "BlendShapeNode.h"
#include "BulgeNode.h"
#include "CameraNode.h"
#include "CheckerNode.h"
#include "CurveNode.h"
#include "DeformerNode.h"
#include "ExtrudeNode.h"
#include "GenericNode.h"
#include "HelperNodes.h"
#include "IKHandleNode.h"
#include "JointNode.h"
#include "LightNode.h"
#include "MayaColorBalanceNode.h"
#include "MayaConstraintNode.h"
#include "MayaEmitterNode.h"
#include "MayaPlaceTextureNode.h"
#include "MayaTransformNode.h"
#include "MeshNode.h"
#include "ParticleNode.h"
#include "ProjectionNode.h"
#include "RampNode.h"
#include "ShaderNode.h"
#include "SineDeformerNode.h"
#include "SkinClusterNode.h"
#include "TangentSpaceNode.h"
#include "TextureBaseNode.h"
#include "TextureNode.h"
#include "TransformVectorNode.h"
#include "VertexAnimationNode.h"
#include "WeightedSumNode.h"

#endif
