set(LLVMJit_DEPENDENCIES Base)

# find dependencies
find_package(llvm NO_MODULE)

set(LLVMJit_PACKAGES llvm)
set(LLVMJit_INCLUDE_DIRS ${LLVM_INCLUDE_DIR})
set(LLVMJit_DEFINITIONS ${LLVM_DEFINITIONS})
set(LLVMJit_LIBRARIES ${LLVM_LIBRARIES} ${CLANG_LIBRARIES})

set(LLVMJit_HAS_INIT_DONE YES)
